### ISSUE TITLE
Sever not building correctly

### ISSUE THREAD

**Issue by JoeBlake80** [zekroTJA/atm9-dockerized#1]
When trying to start the container I am presented with an error message and the container is stuck in "restarting"

INSTALL_ONLY: complete
/var/mcserver/scripts/run.sh: line 8: server.properties: Is a directory

**Comment by zekroTJA** [comment]
If you want to bind files like `server.properties` or `whitelist.json` directly into the container, you need to create the files before creating the container on the host system. Otherwise, docker will create the binds as directory which will the fail on starting the container.

Simply remove the created directories and create them as empty files before starting the container should solve the problem.

**Comment by JoeBlake80** [comment]
That seemed to work thanks.
